### ISSUE TITLE
Typing in number only adds step value

### ISSUE THREAD

**Issue by popboxgun** [junkfix/numberbox-card#1]
I have an input_number that has a step 5, the plus / minus works perfectly, but if I click on the box to get the popup and try to manually adjust the number, it only inputs the step number, ignores 0-4 and 6-9.

**Comment by htmltiger** [comment]
Hmm, i have noticed it, we may need some debouncing function that waits for the input.

**Comment by htmltiger** [comment]
It is same even without this plugin so its a limitation of more info popup box and there is nothing we can do about it.
There is no code in the plugin about what happens in the popup.
