### ISSUE TITLE
Strange values after adjusting

### ISSUE THREAD

**Issue by TTLucian** [junkfix/numberbox-card#15]
Hello! First, thanks! This is a very useful card.
I'm having some problems with the actual value of the input_number helper. I don't know from where this comes but, here it is:

![1](https://user-images.githubusercontent.com/1855276/105952809-c8701f80-607a-11eb-8650-b588967af03b.jpg)

**Comment by htmltiger** [comment]
The card is only requesting to increase/decrease the step value in the original value.
You may have to manually change the original value to a round number first to fix the issue.

https://github.com/home-assistant/frontend/issues/1687

**Comment by azlux** [comment]
I see the same, My temperature was `20.2 °C` , then I click **two times** on the "+" of numberbox-card , and the temp is now  `20,400000000000002 °C `

I think you can reopen this issue

**Comment by azlux** [comment]
It's a float issue from most of programming language, javascript have it too.
![image](https://user-images.githubusercontent.com/11210117/115059317-aef6ab00-9ee6-11eb-942b-d4ac05765d16.png)

I think you need to add a fix here : https://github.com/htmltiger/numberbox-card/blob/main/numberbox-card.js#L80 (not sure, I don't know javascript well)

You know you have a 0.001 max step : https://www.home-assistant.io/integrations/input_number/#step
So you can add : `variable_of_the_value=Math.round(variable_of_the_value*1000)/1000`

**Comment by htmltiger** [comment]
I have updated as suggested. please check the updated version.

Thanks.

**Comment by azlux** [comment]
Looks good to me.
Thank for the changes
