### ISSUE TITLE
Secondary Info and Change Event delay

### ISSUE THREAD

**Issue by alexob** [junkfix/numberbox-card#16]
Hi. Could you please add secondary_info?
Also, will be good if the module will be setting input_number after some delay. For example I want to change number from 10 to 15 and step = 1. I click to "+" 5 times and getting 5 events of change input_number. If I have some delay I will set it to one second (for example) and after my 5 click I will get only one event of change input_number.

**Comment by htmltiger** [comment]
Added change delay.

Any examples about secondary info?

**Comment by alexob** [comment]
> Added change delay.

Thank you. Super! 
Can I set delay in millisecond ?
For example:
`
- entity: input_number.holiday_temp
  type: custom:numberbox-card
  secondary_info: last-changed
  **change_delay: 500**
`

> Any examples about secondary info?

like as in standart input_number and in other cards. For showing time of last change

`
- entity: input_number.holiday_temp
  **secondary_info: last-changed**
`

**Comment by htmltiger** [comment]
Added
```
secondary_info: last-changed
delay: 500
```

**Comment by alexob** [comment]
Thank you.
After these changes your card does not show icon

**Comment by htmltiger** [comment]
the icon and plus/minus shows fine here

**Comment by alexob** [comment]
Plus/minus icons are showing normal, but icon - does not (I just updated card)

**Comment by htmltiger** [comment]
I am using home assistant version 2021.2.1 and on default lovelace theme and it works fine, with or without custom icon and all 3 icons works fine.
what is your config?

**Comment by alexob** [comment]
I had version 2021.1.5 with default lovelace theme. It was working until you did some changes. 
Yesterday, I updated HA to version 2021.2.2 and now icon in your card is working
