### ISSUE TITLE
Impossible to install/update via HACS

### ISSUE THREAD

**Issue by nagyrobi** [junkfix/numberbox-card#17]
When trying to add this via HACS, the following error appears in HA log:
`ERROR (MainThread) [custom_components.hacs] Could not use repository with ID 304967918 ('NoneType' object has no attribute 'attributes')`
Another symptom is that when clicking on the name information is not shown:
![kép](https://user-images.githubusercontent.com/1550668/107491100-02691780-6b8b-11eb-98b7-060547589eac.png)
It hangs like this forever.

I don't think this is a HACS issue because any other component can be added updated, except this. There must be an issue with the repository itself.

**Comment by htmltiger** [comment]
Try updating hacs to latest version 1.11.2 as it works fine here.
There are no changes made in the config file hacs.json

**Comment by nagyrobi** [comment]
Ok fixed now.
