### ISSUE TITLE
 [homeassistant.components.websocket_api.http.connection]  Received invalid command: lovelace/resources/create

### ISSUE THREAD

**Issue by AlanJohnWilliams** [junkfix/numberbox-card#21]
When installing numberbox-card via HACS, the install dialog box hangs with a spinning wheel and the following error is showing up in my homeassistant log:

``
2021-08-05 11:12:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140381625117040] Received invalid command: lovelace/resources/create
``

This is with the latest version of homeassistant, 2021.8.1. HACS version 1.13.2.

Any suggestions for further troubleshooting and fixing? 

Thanks,

**Comment by htmltiger** [comment]
I have just tried reinstalling and works fine with 2021.8.1 HACS 1.13.2 
Can you try and install any other frontend plugin to check if that works?
Seems like problem with ha or hacs installation.

**Comment by AlanJohnWilliams** [comment]
I forgot to add the resource entry to my configuration.yaml as clearly stated in the instructions. Doh. All good now. Thanks and sorry for the trouble.
