### ISSUE TITLE
Shifted to the left

### ISSUE THREAD

**Issue by julienlarivee** [junkfix/numberbox-card#4]
Hi,
Just found out this card. 
It's nice to have a mobile friendly way to set input numbers! 

I just noticed something.
The alignment seems a bit shifted to the left on each side of the line compared to the original input number selector.

![image](https://user-images.githubusercontent.com/55027006/99208630-06a1b680-278f-11eb-8312-73ed4f043923.png)

Thanks

**Comment by htmltiger** [comment]
```+``` button has bigger touch area so nothing can be done about right side.

On the left side in default theme it works fine, no idea how to have default spacing.
you can try card mod to have custom styles
