### ISSUE TITLE
Press effect stays on mobile device

### ISSUE THREAD

**Issue by eyalcha** [junkfix/numberbox-card#9]
On mobile device (Android), when pressing the - / + buttons, a grey circle is shown to highlight the press but it stays and doesn't disappear

**Comment by htmltiger** [comment]
no idea how to remove focus

**Comment by MeisterBob** [comment]
in Chrome 87.0.4280.141 on Android 10 that works fine.

**Comment by htmltiger** [comment]
This should be fixed now
